# Generated by Django 6.0.4 on 2026-04-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
