# Generated by Django 6.0.4 on 2026-06-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0009_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
