# Generated by Django 6.0.4 on 2026-06-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0010_profile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
    ]
